"""OpenCode harness adapter.

Verified sources (consulted 2026-09-28):

- https://opencode.ai/v2/docs/agents
- https://opencode.ai/v2/docs/skills
- https://opencode.ai/v2/docs/migrate-v1
- https://github.com/anomalyco/opencode/issues/50598

Rules applied:

- agents are generated into ``.opencode/agents/<id>.md`` (plural)
- frontmatter is generated by this adapter, never copied verbatim
- skills are NOT mirrored; OpenCode reads ``.agents/skills`` (and
  ``.claude/skills``) natively
- the only entrypoint is ``AGENTS.md`` (no per-harness copy)
"""

from _base import (
    Adapter as BaseAdapter,
    ensure_entrypoint,
    iter_workers,
    render_frontmatter,
    write_generated,
)


class Adapter(BaseAdapter):
    id = "opencode"
    executable = "opencode"
    marker_dir = ".opencode"
    agents_dir = ".opencode/agents"
    supports_skills_mirror = False

    def capabilities(self):
        return {
            "skills": True,
            "subagents": True,
            "parallel_agents": True,
            "human_approval": True,
            "persistent_context": True,
        }

    def sync(self, ctx, dry_run=False):
        changes = [ensure_entrypoint(ctx, dry_run=dry_run)]
        for worker in iter_workers(ctx):
            frontmatter = {
                "description": worker.frontmatter.get("description", worker.name),
                "mode": "subagent",
            }
            content = render_frontmatter(frontmatter) + "\n" + worker.body.rstrip() + "\n"
            path = ctx.root / self.agents_dir / f"{worker.name}.md"
            changes.append(write_generated(path, content, dry_run=dry_run))
        return changes

    def invoke(self, ctx, worker, unit=None):
        native = f"native route: @{worker} in chat (subagent file {self.agents_dir}/{worker}.md, mode: subagent)"
        return self._invoke(ctx, worker, unit, native=native)
